const API_URL = 'http://localhost:3000';
const GARAGE = `${API_URL}/garage`;
const ENGINE = `${API_URL}/engine`;
const WINNERS = `${API_URL}/winners`;

const COUNT_RANDOM_CAR = 100;

const CAR_IN_PAGE = 7;

const WINNERS_IN_PAGE = 10;

const COUNT_RANDOM_COLOR = 6;
const HEX_LETTERS = '0123456789ABCDEF';

export { GARAGE, ENGINE, WINNERS, COUNT_RANDOM_COLOR, HEX_LETTERS, COUNT_RANDOM_CAR, CAR_IN_PAGE, WINNERS_IN_PAGE };
